controller_list:
  - name: fake_arm_controller
    type: $(arg execution_type)
    joints:
      - rod_wth_cylin_joint
      - dual_redrod_joint
      - sub_claw_part_1_joint
  - name: fake_gripper_controller
    type: $(arg execution_type)
    joints:
      - claw_1_joint
      - claw_2_joint
initial:  # Define initial robot poses.
  - group: arm
    pose: home
  - group: gripper
    pose: open